[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sitemapy"
version = "0.1.3"
readme="README.md"
authors = [
    { name="Graham Schmidt", email="graham.n.schmidt@gmail.com" },
]
description = "Python package that generates SEO-friendly XML sitemaps"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "defusedxml==0.7.0",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[project.urls]
Homepage = "https://github.com/Graham-Schmidt/sitemapy"
Issues = "https://github.com/Graham-Schmidt/sitemapy/issues"